[package]
name = "step-parser"
version = "0.1.0"
authors = ["Paul Wei√üenbach <paul.weissenbach@aon.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1"
pest_derive = "2.1"
